# http://manuals.bioinformatics.ucr.edu/home/R_BioCondManual#R_clustering
testRClustering = function(){
  # generate a sample data set
  y <- matrix(rnorm(50), 10, 5, dimnames=list(paste("g", 1:10, sep=""), paste("t", 1:5, sep=""))) # Creates a sample data matrix.
  
  scale(t(y)); yscaled <- t(scale(t(y))); apply(yscaled, 1, sd)
  # The function scale() centers and/or scales numeric matrices column-wise. When used with its default settings, the
  # function returns columns that have a mean close to zero and a standard deviation of one. For row-wise scaling the
  # data set needs to be transposed first using the t() function. Another transposing step is necessary to return the
  # data set in its original orientation (same row/column assignment). Centering and scaling are common data transformation
  # steps for many clustering techniques. 
  
  dist(y, method = "euclidean")
  # Computes and returns a distance matrix for the rows in the data matrix 'y' using the specified distance measure, here 'euclidean'.
  c <- cor(t(y), method="spearman"); d <- as.dist(1-c); d
  # To obtain correlation-based distances, one has to compute first a correlation matrix with the cor() function. Since this
  # step iterates across matrix columns, a transpose 't()' step is required to obtain row distances. In a second step the distance
  # matrix object of class "dist" can be obtained with the as.dist() function.
  
  y <- matrix(rnorm(50), 10, 5, dimnames=list(paste("g", 1:10, sep=""), paste("t", 1:5, sep=""))) # Creates a sample data set.
  c <- cor(t(y), method="spearman"); d <- as.dist(1-c); hr <- hclust(d, method = "complete", members=NULL)
  # This is a short example of clustering the rows of the generated sample matrix 'y' with hclust. Seven different cluster joining
  # methods can be selected with the 'method' argument: ward, single, complete, average, mcquitty, median and centroid. The
  # object returned by hclust is a list of class hclust which describes the tree generated by the clustering process with the
  # following components: merge, height, order, labels, method, call and dist.method.
  par(mfrow = c(2, 2)); plot(hr, hang = 0.1); plot(hr, hang = -1)
  # The generated tree can be plotted with the plot() function. When the hang argument is set to '-1' then all leaves end on
  # one line and their labels hang down from 0. More details on the plotting behavior is provided in the hclust help document (?hclust).
  plot(as.dendrogram(hr), edgePar=list(col=3, lwd=4), horiz=T)
  # To plot trees horizontally, the hclust tree has to be transformed into a dendrogram object.
  unclass(hr) # Prints the full content of the hclust object.
  str(as.dendrogram(hr)) # Prints dendrogram structure as text.
  hr$labels[hr$order] # Prints the row labels in the order they appear in the tree.
  par(mfrow=c(2,1)); hrd1 <- as.dendrogram(hr); plot(hrd1); hrd2 <- reorder(hrd1, sample(1:10)); plot(hrd2); labels(hrd1); labels(hrd2)
  # Example to reorder a dendrogram and print out its labels.
  library(ctc); hc2Newick(hr)
  # The 'hc2Newick' function of the Bioc 'ctc' library can convert a hclust object into the Newick tree file format for export
  # into external programs.  
}